version: '3'
services:
    web:
        image: marcelormourao/uni7-cloud-native:1.0.1
        ports: 
            - "8080:8080"
        networks: 
            - demo-network
    other:
        image: "allanfvc/uni7sum:1.0.0"
        ports: 
            - "8082:8080"
        networks: 
            - demo-network
networks: 
  demo-network:
    driver: bridge