apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: marcelormourao/uni7-cloud-native:1.0.2
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "800Mi"
            cpu: "800m"
        ports:
        - name: myapp-port
          containerPort: 8080
